### ISSUE TITLE
1 Add Search Bar to Nav. Bar

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN341-W2018#12]
In the navigation bar, there should be a search bar with a maximum of 100 characters (for now), and a button to send the search query to the server.

**Comment by TSer1111** [comment]
Search bar now passes the searched item to the server and then redirects to the "/search" page.

**Comment by TSer1111** [comment]
Search bar will return error message to user if the searched item is less than 1 char or more than 100 char.
Done via HTML validation.
