### ISSUE TITLE
1 Log-In/Sign-up Page

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#2]
The LHS is the log-in area (include log-in form)
The RHS is the sign-up area (include sign-in form)
both forms include only E-mail and Password.

**Comment by TSer1111** [comment]
Login/Signup page completed following the structure defined.
Forms send the information to the server. Now it's up to the backend.

Might have to go back and add nicer css.

**Comment by aa-software2112** [comment]
Don't worry about the css, we will make a future user story for beautifying the site. Nice work
