### ISSUE TITLE
1 Submit answer

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#20]
Answer body: char upper limit 1000, lower limit 1
Submit answer button (check the if the answer if empty)
     case1: Invalid due to empty answer, display an appropriate message.
     case2: Valid, send the answer to the server.

**Comment by TSer1111** [comment]
Answer page currently has a textbox for the user to enter the answer.
It will not submit when empty, and cannot have more than 1000 characters.

Missing the DB hookup, but form data is successfully sent over the server.
