### ISSUE TITLE
Query for newest 10 questions doesn't get all answers

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN341-W2018#208]
It seems that if a user posted one or more questions, but no one answered any of them, the questions don't show up on the home page (10 newest) even though one of those questions may be the most recent one.

**Comment by aa-software2112** [comment]
There is also the issue where the same question duplicates (for some reason)

**Comment by Legendary-Griffin** [comment]
I'll try to fix that tomorrow :)

**Comment by AleexCh** [comment]
About the bug on the homepage, I was kinda talking about it last meeting, and I think I didn't make myself clear. The possible problem is within the query here : 

line 31 on homepage.js
>>>>>FROM question JOIN user ON question.user_id=user.user_id JOIN answer ON question.user_id=answer.user_id \  <<<<<   .

 It only looks for questions with the same user_id in the answer and question table, eventhough the user_id in the answer's table is the user who  ANSWERED a question and the user_id on the question table is a user who made the QUESTION.

Possible solution: 
when you delete "answer.answer_body AS answers," on line 27 and  "JOIN answer ON question.user_id=answer.user_id" on line 31 and restart the server you get the correct latest 10

**Comment by AleexCh** [comment]
This was fixed by @jasonckc
