### ISSUE TITLE
Register functionality

### ISSUE THREAD

**Issue by jasonckc** [aa-software2112/SOEN341-W2018#291]
As soon as a user registers an account, he will see the user profile tab in the nav bar, instead of the log in tab. while he has not logged in yet. When he clicks on the user profile tab, he will not be redirected to the right user profile page.

**Comment by AleexCh** [comment]
On the header.ejs file, the if statemen on line 39 states <% if (typeof username === "undefined") { %>, but when redirected after signing up, the typeof username is not undefined anymore, so it goes to the else statement on line 45

**Comment by AleexCh** [comment]
Solutions found: Make a new header for after_signup.ejs that only shows the login/singup button.

**Comment by jasonckc** [comment]
Fixed.
