### ISSUE TITLE
2 E-mail validation

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#3]
The E-mail validation for both log-in and sign-up will be through client-side JS. 
The E-mail validation is to check if it's an E-mail (don't need to check for availability yet).
e.g validate_email (email)
Case Sign-Up
       case1: Valid, jump to password validation.
       case2: Invalid, display an appropriate message.
Case Log-In
       case1: Valid, jump to Log-in.
       case2: Invalid, display an appropriate message.

**Comment by TSer1111** [comment]
Completed via the HTML validation system.
Form cannot be submitted if there isn't a proper email structure (required @ in it).
If an improper format is entered, a message will tell the user to correct it.
