### ISSUE TITLE
3 Password validation(Sign-Up)

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#4]
The passwords validation is only on the sign-up form using client-side JS. 
The password validation is to check the length of the password (6<password<16)
This functionality can be expanded later based on client demands. 
e.g. validate_password(password)
Case 1: Valid, jump to E-mail availability (Sign-up)
Case 2: Invalid, return an appropriate message

**Comment by TSer1111** [comment]
Completed via HTML validation system.
Passwords will not be accepted unless they are between 6 - 12 characters.
A message is displayed if the user is not within that range and form cannot be submitted until it is fixed.

**Comment by aa-software2112** [comment]
@TSer1111 We can remove the validation from the login because it will do that by checking if it matches in the database, no need to prevent a user from making a failed attempt at login

**Comment by TSer1111** [comment]
Ok, I removed the HTML validation from the login form.
