### ISSUE TITLE
4 E-mail availability(Sign-Up)

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#5]
Once E-mail and password validation pass, send the data to the server and query the database1 for the E-mail to check if it already exists and return messages
case1: The E-mail already exists. Return an appropriate message
case2: It is a new E-mail. Write the E-mail and Password to the database1. Return an appropriate message

**Comment by TSer1111** [comment]
Issue is for the website prototype. If needed, an issue will opened for the current site in the correct project.

No longer valid. Closing.
