### ISSUE TITLE
6 Log-In

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#6]
Once the E-mail validation for log-in is passed, send the E-mail and password to the server, and query the database for the E-mail.
Case 1: The E-mail doesn't exist in the database, return appropriate message
Case 2: The E-mail exists, check the password
              2.1 If the passwords don't match, display appropriate message
              2.2 If the passwords match, store user properties from DB1 on the server in a variable. 
                    Display appropriate message.

**Comment by TSer1111** [comment]
Issue is from website prototype. Issue is implemented on current site. No longer valid. Closing.
