### ISSUE TITLE
1 Post Questions page

### ISSUE THREAD

**Issue by shushengfuqin** [aa-software2112/SOEN341-W2018#9]
Title: Upper limit of 100 Char, lower limit of 1 char
Body: Upper limit of 1000 Char, lower limit of 1 char.
Submit button 
    case1: Submit successfully, jump to store question into the DB.
    case2: Unsuccessful due to empty title or body, return message. 
    case3: User, not logged-in, return message and show log-in/sign-up button which redirects the 
                user to the log-in/sign-up page.

**Comment by TSer1111** [comment]
Post Question page is created according to the listed specs.
Empty text boxes are refused, and the page will not let the user enter more than the specified characters.
Data is successfully capture by "post" upon submission.

**Comment by aa-software2112** [comment]
@TSer1111 This is not completed as we must have an option for users to go to a login/signup page if they are not logged in. Create another issue that consist of just the text area/submission and mark that one as "done".

**Comment by TSer1111** [comment]
The one I submitted automatically redirects to the login page when a user tries to ask a question when not logged in.

I will update it to give them the option.

**Comment by TSer1111** [comment]
Issue from website prototype. No longer valid.
