### ISSUE TITLE
Make href take the form /question_forum/<question_id>

### ISSUE THREAD

**Issue by aa-software2112** [aa-software2112/SOEN341-W2018#92]
Once all the links to questions are displayed after a search his attempted, all links should have a href value that requests the link @ href="/question_forum/<question_id>" in order to interface with the question_forum app.get() listener.

**Comment by TSer1111** [comment]
href currently leads to a link of that format, but it is no yet connected to any question.
Will lead to in invalid page until question id is passed through.
